version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/collector"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "cargo"
    directory: "/bpf"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
